# Generated by Django 4.2 on 2024-10-04 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_category',
            field=models.CharField(choices=[('etudiant', 'etudiant'), ('chercheur', 'chercheur'), ('docteur', 'docteur'), ('enseignant', 'enseignant')], default='etudiant', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='reservations',
            field=models.ManyToManyField(related_name='reservations', through='user.reservation', to='conference.conference'),
        ),
        migrations.AddField(
            model_name='participant',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
