# Generated by Django 4.2 on 2024-10-11 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_conference_capacity_alter_conference_program_and_more'),
        ('user', '0002_participant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Participant',
            new_name='participant',
        ),
        migrations.AlterField(
            model_name='participant',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Le CIN doit contenir exactement 8 caractères numériques.')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@esprit\\.tn$', "L'adresse email doit appartenir au domaine esprit.tn.")]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('conference', 'participant')},
        ),
    ]
