# Generated by Django 4.2 on 2024-10-11 09:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100, message='capacity must be under 100')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.FileField(upload_to='files/daloul', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'], message='the type should only be what i say')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 10, 11)),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2024, 10, 11))), name="The start date must be greater than today's date"),
        ),
    ]
